### PR TITLE
Etch large literals

### PR DESCRIPTION
**Pull request by robertdickson**
This PR introduces the Fixed128 class, and provides support for mutable 1.234fp128 literals.

### CODE REVIEW

**Review by troels-im — DISMISSED** [review]
LGTM

**Comment by ejfitzgerald** [comment]
@robertdickson is this is ready to merge please add the flag and then @fetch-bot can land it

**Comment by robertdickson** [comment]
@ejfitzgerald My bits on this PR are done, but I handed over completion of some of the arithmetic operators to @markos, which he is currently working on.

**Comment by markos** [comment]
It seems that @pbukva has been working in parallel on a feature that is needed for this to be completed in #1993, in particular state serialization/deserialization for larger objects. I had done something similar but for Fixed128 only. Since his method is more generic, and I can just extend it with Fixed128 as a special case, I will wait for 1993 to be merged. For this reason, this PR should not wait.

**Review by markos — APPROVED** [review]
Looks good

**Pull request merged**
