### PR TITLE
Remove redundant wrapper stage; make stage names uniform

### PR DESCRIPTION
**Pull request by wkaluza**

### CODE REVIEW

**Review by n-hutton — DISMISSED** [review]
lgtm

**Review by ejfitzgerald — CHANGES_REQUESTED** [review]
I can't see and stages being run on CI for this build. Am I going mad? 😁

**Comment by wkaluza** [comment]
> I can't see and stages being run on CI for this build. Am I going mad? grin

There's a backlog, I'm stuck in the queue: https://jenkins.economicagents.com/blue/organizations/jenkins/fetch-ledger/activity/

It seems GitHub doesn't know to expect a build until one is already under way. Jenkins won't report that a build is in progress until it actually begins the run. In any case, I'm not going to merge until I have a passing build.

**Comment by wkaluza** [comment]
@ejfitzgerald It's running now.

**Review by ejfitzgerald — DISMISSED** [review]

**Comment by wkaluza** [comment]
Need re-approval due merge conflicts

**Review by ejfitzgerald — APPROVED** [review]

**Pull request merged**
