### PR TITLE
Feature/remove dead code

### PR DESCRIPTION
**Pull request by n-hutton**
The following appear to be dead code (not even included anywhere in the codebase)

```
./libs/core/include/core/containers/vector.hpp
./libs/core/include/core/serializers/serialisation_argument_wrapper.hpp
./libs/core/include/core/serializers/serialisation_verbatim_wrapper.hpp
./libs/core/include/core/type_util.hpp
./libs/core/include/core/yml/yml_document.hpp
./libs/http/include/http/middleware/color_log.hpp
./libs/http/include/http/session.hpp
./libs/ledger/include/ledger/chain/helper_functions.hpp
./libs/ledger/include/ledger/protocols/executor_rpc_service.hpp
./libs/meta/include/meta/value_util.hpp
./libs/network/examples/advanced_rpc/vector_serialize.hpp
./libs/network/examples/quick_start/node.hpp
./libs/network/include/network/generics/subscriptions_container.hpp
./libs/network/include/network/p2pservice/node_details.hpp
./libs/network/include/network/p2pservice/resolver.hpp
./libs/network/include/network/service/abstract_decorator.hpp
./libs/network/include/network/test-helpers/muddle_test_client.hpp
./libs/network/include/network/test-helpers/muddle_test_definitions.hpp
./libs/network/include/network/test-helpers/muddle_test_server.hpp
./libs/network/tests/include/helper_functions.hpp
./libs/vm/include/vm/pointer_register.hpp

```

### CODE REVIEW

**Comment by wkaluza** [comment]
As far as I remember, @ejfitzgerald wanted to preserve the files in `libs/miner`.

Did you write a script to generate this list? Might be worth making that a CI check.

**Comment by n-hutton** [comment]
> As far as I remember, @ejfitzgerald wanted to preserve the files in `libs/miner`.
> 
> Did you write a script to generate this list? Might be worth making that a CI check.

Ah yeah I am sure that some amount of these will be preserved/dropped from this PR on people's request. Just a bit of a spring clean - I wouldn't make this a ci check

**Comment by markos** [comment]
@n-hutton Please do not remove any files under the vectorise/ tree, there is planned work on this.

**Comment by n-hutton** [comment]
@markos sure!

**Comment by ejfitzgerald** [comment]
@n-hutton can we keep the annealer miner code a little bit longer. It is not used currently but we will need to reintegrate it as soon as we start getting a consistent queue length on the mining pool.

**Comment by n-hutton** [comment]
@ejfitzgerald annealer miner removed from list

**Comment by wkaluza** [comment]
@n-hutton you reverted the deletion of annealer miner, but I think all of the files in miner are dependent on one another. I ran into this the first time when trying to delete them. I'd double-check what includes what in that directory before you nuke it - it doesn't make sense to keep annealer miner without any of the dependencies that it alone requires.

**Comment by n-hutton** [comment]
> @n-hutton you reverted the deletion of annealer miner, but I think all of the files in miner are dependent on one another. I ran into this the first time when trying to delete them. I'd double-check what includes what in that directory before you nuke it - it doesn't make sense to keep annealer miner without any of the dependencies that it alone requires.

That makes sense :)

**Pull request merged**
