### PR TITLE
Enable charge estimators for object operators

### PR DESCRIPTION
**Pull request by wkaluza**

### CODE REVIEW

**Comment by wkaluza** [comment]
@jrriehl FYI

**Review by baykaner — COMMENTED** [review]
seems great to me, but @robertdickson will need to review

**Review by robertdickson — DISMISSED** [review]
LGTM

**Review by ejfitzgerald — DISMISSED** [review]
Looks good from my side

**Review by ejfitzgerald — DISMISSED** [review]

**Review by baykaner — DISMISSED** [review]

**Review by baykaner — APPROVED** [review]

**Pull request merged**
