### PR TITLE
Re-enable unreliable tests

### PR DESCRIPTION
**Pull request by wkaluza**

### CODE REVIEW

**Comment by n-hutton** [comment]
I think we need to re-enable these flaky tests only (and as a priority) if there is a corresponding fix to the flakyness - I also just noticed that ```thread_pool_gtest``` timed out on another PR

**Comment by wkaluza** [comment]
Yes.

**Comment by n-hutton** [comment]
Looks like that makes it containers, network, muddle and thread_pool. Maybe we should divvy them up in the next sprint (?)

**Comment by wkaluza** [comment]
Close temporarily to reduce load on CI

**Pull request closed without merging**
