### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by devjsc**
Updated Fetch.AI names.

### CODE REVIEW

**Review by ejfitzgerald — DISMISSED** [review]
👍

**Comment by ejfitzgerald** [comment]
@devjsc will merge once the CI checks have completed

**Comment by devjsc** [comment]
One more teeny .AI addition!

**Review by ejfitzgerald — APPROVED** [review]

**Comment by ejfitzgerald** [comment]
@devjsc you will need to merge the latest `master` into your branch to fix the CI issues

**Pull request merged**
