### PR TITLE
Do not trim cabinet history after reversion

### PR DESCRIPTION
**Pull request by wkaluza**

### CODE REVIEW

**Review by ejfitzgerald — CHANGES_REQUESTED** [review]
Not sure this includes my updates from the release branch

**Comment by wkaluza** [comment]
Your uppance will come, fetch-bot.

**Review by ejfitzgerald — CHANGES_REQUESTED** [review]
Still can't see the updates in constellation I was expecting here. Am I missing something?

**Comment by wkaluza** [comment]
The update to `constellation.cpp` you are referring to went in as part of #2297 and is already on `master`. For this reason it does not show up in the aggregate diff of this PR.

**Review by ejfitzgerald — APPROVED** [review]

**Comment by ejfitzgerald** [comment]
This is now included in #2317

**Pull request closed without merging**
